# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Olivia Bishop
description:      'Android engineer at Facebook'
url:              http://obishop89.github.io
baseurl:          'http://obishop89.github.io/'
paginate:         5

author:
  name:           'Olivia Bishop'
  url:            https://obishop89.github.io

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/obishop89/obishop89.github.io
